name: "Home Assistant User Interface (UI) Dashboard Designer"
description: "An add-on to allow hosting dashboards outside of the Home Assistant User Interface"
version: "1.0.0"
slug: "mekatrol_homeassistant_ui_designer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
