app:
  home_assistant_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlOWEwMjI4ODhlZTg0NTI1OGYwNGIyMTcxMjVkMTgyMyIsImlhdCI6MTc1MDUwMzM4NiwiZXhwIjoyMDY1ODYzMzg2fQ.ISXES8h7omKiHAHgm9478wRcZPog-AgKCgNv9L3e1B0
