import { fileURLToPath, URL } from 'node:url';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueDevTools from 'vite-plugin-vue-devtools';
import { compileSfcComponentPlugin, excludeSfcComponentPlugin } from './tools/build-plugin';

export default defineConfig({
  plugins: [vue(), vueDevTools(), compileSfcComponentPlugin(), excludeSfcComponentPlugin()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  build: {
    outDir: '../designer-server/web/static',
    emptyOutDir: true // Clean out static files folder, they are all generated by this build
  }
});
